# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4745b3dd602b659c363202800cd5da950724b83253113309323810ca8d90ea2e1ccf1d51d8dfe53dab96cad4efeaa6f71b2dd36dd152b049a056af0cc0190e05

test:
  secret_key_base: 605649a9ef6ef9dbde2e8c4982d5c1aee3a3d67a3a5fcb0fa4f9fc0bb29d401febb481a06b11567a403201125ff74f81992a4c5caf485289970c5b3b4d08e66f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
